version: "3"

services:
  hub:
    image: aihub_server:1.0
    ports:
      - "8001:8000"
    env_file:
      - ./temp_env_files/hub.env
    depends_on:
      - db
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - ./temp_env_files/db.env
  ctms:
    image: aihub_ctms:1.0
